// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeAutomaticMode(arg1) {
  return window['go']['main']['App']['ChangeAutomaticMode'](arg1);
}

export function ChangeBrushFunc(arg1) {
  return window['go']['main']['App']['ChangeBrushFunc'](arg1);
}

export function ChangeMapNum(arg1) {
  return window['go']['main']['App']['ChangeMapNum'](arg1);
}

export function ChangeOverMap(arg1) {
  return window['go']['main']['App']['ChangeOverMap'](arg1);
}

export function ChangePeopleNum(arg1) {
  return window['go']['main']['App']['ChangePeopleNum'](arg1);
}

export function ChangeSkillNum(arg1) {
  return window['go']['main']['App']['ChangeSkillNum'](arg1);
}
