// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeAutomaticMode(arg1:string):void;

export function ChangeBrushFunc(arg1:string):void;

export function ChangeMapNum(arg1:string):void;

export function ChangeOverMap(arg1:string):void;

export function ChangePeopleNum(arg1:string):void;

export function ChangeSkillNum(arg1:string):void;
